### ISSUE TITLE
Error after changing password

### ISSUE THREAD

**Issue by rabol** [ryangjchandler/filament-profile#2]
I get this error after pressing cancel on the profile page

The GET method is not supported for this route. Supported methods: POST.

steps
Go to the profile page
change your password
press save
you will still be on the profile page
press cancel

then you will get the error

**Comment by ryangjchandler** [comment]
Ah, this is because the Cancel button is quite naive and just uses `url()->current()`. After you've saved, the view gets re-rendered and the button ends up having the Livewire POST route instead.

I'd welcome a PR to fix this, if you'd like? Would just be a case of replacing it with the page's actual URL.
